// sidebars.js
module.exports = {
  docsSidebar: [
    {
      type: 'autogenerated',
      dirName: '.',
    },
  ],

  memoSidebar: [
    {
      type: 'autogenerated',
      dirName: '.',
    },
  ],
};